baseURL = 'https://s414june.github.io/xmasGift/'
languageCode = 'zh-TW'
HasCJKLanguage = true
title = 'My New Hugo Site'
theme = 'hugo-pacman-theme'

pygmentsStyle = "default"
pygmentsUseClasses = true

[Author]
  # Name = "your-name"

[outputs]
  home = [ "RSS", "HTML" ]
    
[outputFormats] 
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[Params]
  # AuthorHomepage = "your-home-page"-
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = ""
  Subtitle = "subtitle"
  Weibo = ""
  WeiboID = 123
  Twitter = ""
  GitHub = ""
  Facebook = ""
  LinkIn = ""
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  CreativeCommons = true
  MathJax = false

  [Params.GoogleAnalytics]
    ID = ""
    gtag_ID = ""

  [Params.Disqus]
    ShortName = ""

  [Params.Strings]
    Search = "search"
    PageNotFound = "頁面不存在"
    ShowSideBar = "顯示側邊欄"
    HideSideBar = "隱藏側邊欄"
    Categories = "分類"
    Archive = "時間"
    Tags = "標籤"
    Rss = "RSS 訂閱"
    TableOfContents = "文章目錄"

[Menu]
  [[Menu.Main]]
    Name = "home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "about"
    URL = "/about"
    Weight = 2

